const d = "$";

export const BASH_COMPLETION = [
  `_gmux_commands="list doctor scripts attach detach kill rename git completion"`,
  `_gmux_scripts="cleanup health export stats auto-commit branch-cleanup conflict-helper pr-ready watcher notifier logger backup restore diagnostics"`,
  `_gmux_git_commands="status diff log blame stash conflict"`,
  ``,
  `_gmux_list_sessions() {`,
  `  local store="${d}HOME/.gmux/sessions.json"`,
  `  if [[ -f "${d}store" ]]; then`,
  `    python3 -c "import json,sys; d=json.load(open('${d}store')); [print(k) for k in d]" 2>/dev/null || return 0`,
  `  fi`,
  `}`,
  ``,
  `_gmux_completions() {`,
  `  local cur="${d}{COMP_WORDS[COMP_CWORD]}"`,
  `  local prev="${d}{COMP_WORDS[COMP_CWORD-1]}"`,
  `  local cmd="${d}{COMP_WORDS[1]}"`,
  ``,
  `  if [[ ${d}COMP_CWORD -eq 1 ]]; then`,
  `    mapfile -t COMPREPLY < <(compgen -W "${d}_gmux_commands" -- "${d}cur")`,
  `    return 0`,
  `  fi`,
  ``,
  `  case "${d}cmd" in`,
  `    scripts)`,
  `      if [[ ${d}COMP_CWORD -eq 2 ]]; then`,
  `        mapfile -t COMPREPLY < <(compgen -W "${d}_gmux_scripts" -- "${d}cur")`,
  `      fi`,
  `      ;;`,
  `    attach|detach|kill)`,
  `      if [[ ${d}COMP_CWORD -eq 2 ]]; then`,
  `        mapfile -t COMPREPLY < <(compgen -W "${d}(_gmux_list_sessions)" -- "${d}cur")`,
  `      fi`,
  `      ;;`,
  `    git)`,
  `      if [[ ${d}COMP_CWORD -eq 2 ]]; then`,
  `        mapfile -t COMPREPLY < <(compgen -W "${d}_gmux_git_commands" -- "${d}cur")`,
  `      fi`,
  `      ;;`,
  `    completion)`,
  `      if [[ ${d}COMP_CWORD -eq 2 ]]; then`,
  `        mapfile -t COMPREPLY < <(compgen -W "bash zsh" -- "${d}cur")`,
  `      fi`,
  `      ;;`,
  `    list|doctor)`,
  `      mapfile -t COMPREPLY < <(compgen -W "--json --verbose" -- "${d}cur")`,
  `      ;;`,
  `  esac`,
  ``,
  `  case "${d}prev" in`,
  `    -A|--agent)`,
  `      mapfile -t COMPREPLY < <(compgen -W "codex pi aider claude-code" -- "${d}cur")`,
  `      ;;`,
  `    -a|--agents)`,
  `      mapfile -t COMPREPLY < <(compgen -W "1 2 3 4 5 6 7 8" -- "${d}cur")`,
  `      ;;`,
  `  esac`,
  `}`,
  ``,
  `complete -F _gmux_completions gmux`,
].join("\n");

export const ZSH_COMPLETION = [
  `_gmux_commands="list doctor scripts attach detach kill rename git completion"`,
  `_gmux_scripts="cleanup health export stats auto-commit branch-cleanup conflict-helper pr-ready watcher notifier logger backup restore diagnostics"`,
  `_gmux_git_commands="status diff log blame stash conflict"`,
  ``,
  `_gmux_list_sessions() {`,
  `  local store="${d}HOME/.gmux/sessions.json"`,
  `  if [[ -f "${d}store" ]]; then`,
  `    python3 -c "import json,sys; d=json.load(open('${d}store')); [print(k) for k in d]" 2>/dev/null`,
  `  fi`,
  `}`,
  ``,
  `_gmux() {`,
  `  local context state state_descr line`,
  `  typeset -A opt_args`,
  ``,
  `  _arguments -C \\`,
  `    '1:command:->commands' \\`,
  `    '*::subcmd:->subcmd'`,
  ``,
  `  case ${d}state in`,
  `    commands)`,
  `      _describe 'command' _gmux_commands`,
  `      ;;`,
  `    subcmd)`,
  `      case ${d}line[1] in`,
  `        scripts)`,
  `          _describe 'script' _gmux_scripts`,
  `          ;;`,
  `        attach|detach|kill)`,
  `          _arguments '2:session:($(_gmux_list_sessions))'`,
  `          ;;`,
  `        git)`,
  `          _describe 'subcommand' _gmux_git_commands`,
  `          ;;`,
  `        completion)`,
  `          _arguments '2:shell:(bash zsh)'`,
  `          ;;`,
  `        list|doctor)`,
  `          _arguments '-j[--json]' '-v[--verbose]'`,
  `          ;;`,
  `      esac`,
  `      ;;`,
  `  esac`,
  `}`,
  ``,
  `compdef _gmux gmux`,
].join("\n");

export function getCompletion(shell: string): string | null {
  if (shell === "bash") return BASH_COMPLETION;
  if (shell === "zsh") return ZSH_COMPLETION;
  return null;
}
